/*
---------------JSON-------------------
#JSON (JavaScript Object Notation) is a lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate.
#It is primarily used to transmit data between a server and a web application as text.

#JSON is language-independent, but it uses conventions that are familiar to programmers of the C family of languages, which includes C, C++, C#, Java, JavaScript, Perl, Python, and many others.
#JSON is built on two structures:
1. A collection of name/value pairs (often called an object).
2. An ordered list of values (often called an array).
#JSON is often used to serialize and transmit structured data over a network connection, typically between a server and a web application.

Key Features of JSON:
1. Lightweight: JSON is a lightweight data format, making it easy to transmit over networks.
2. Readable: JSON is human-readable, meaning it can be easily understood and edited by humans.
3. Language-Independent: JSON is language-independent, meaning it can be used with various programming languages.
4. Easy to Parse: JSON can be easily parsed and generated by most programming languages.
5. Supports Nested Structures: JSON supports nested objects and arrays, allowing for complex data structures.
6. Data Interchange: JSON is commonly used for data interchange between a server and a web application.
7. Text-Based: JSON is a text-based format, making it easy to transmit over networks.
8. No Comments: JSON does not support comments, making it a pure data format.
9. Strict Syntax: JSON has a strict syntax, requiring double quotes for strings and keys.
10. No Functions: JSON does not support functions or methods, making it a pure data format.

#JSON Syntax:
1. Data is represented as key/value pairs.
2. Keys must be strings enclosed in double quotes.`
3. Values can be strings, numbers, objects, arrays, booleans (true/false), or null.
4. Objects are enclosed in curly braces {}.
5. Arrays are enclosed in square brackets [].
6. Strings must be enclosed in double quotes.
7. JSON does not support comments.
8. JSON is case-sensitive.
9. JSON does not support trailing commas.(a comma after the last item in an object or array).

*/

//convert javascript object to JSON:
//  Use JSON.stringify() method to convert a JavaScript object to a JSON string.

const user = {name: "divyanshu", age:21}
const jsonString = JSON.stringify(user)
// console.log(jsonString);// {"name":"divyanshu","age":21} // this is a JSON string.

//now we are going to convert JSON string to javascript object.
const user1 =`{"name": "divynshu", "last name": "maurya", "age":30}`
const object = JSON.parse(user1)
// console.log(object);// { name: 'divynshu', last name: 'maurya', age: 30 } // this is a javascript object.


